---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBq6YdrwQn9cVvQOgqVZz3X37od046TURyt8izcSGjtM32MZT9aE3E1vyUTNJaHpVACahQjgPhFVhJTxhYsWiu564hQD716fU1OE4samXxV02j9BZoQj0QFOjjtWSIxXHd+TmB3LN2h97KMB2N3+5f7khAI42SLPigFygO0ZjES1X54IqZX+rYEvFfozaPe5sUkWuFAllM6Sx/vWo8rQREHdPrKg9j30Df0Q6dj3c2ccfQO8o37UmJXlb8/OFRJ0fbU/9W56qf848+rthY1Bc8uc1XDAy+s/ICVPkVVe15NCWMdH2QunyhkJjxYHAZmZImDVHTYoebbaEmeOO3uXfhLs+Fc2yX4lZccpkknzmk28g7Ln8ORpu1P7aAmvI588OV5tKfSKSJmeXRE8FNnpEqLAdavAOqLv3W1Hto03XGzuj4WSN3aiCicRPob4/b2MTNkLTcCWntoju46OQBxkCM7xU0uxVt3vBFR7hQV4PSV0WNznA36rSVAV41Kem4Aipk5+RFcz6hFFFDpgqeHjRZG+8w9AcRHzaD26C+ua4crphkBQZEOSsTEtAOtMTNnvVRqdpMltSvh+v09M55lIaPzmRjHMLlJqdJ1hpRFRX1WHh4EwrP/ePNGSiJigzbGer1hI2blwcepU4vwGVIWO1+6oD8WGDJhJeGbIBOvKFRivV9CXMjfmAPVtOpi1OPs2GxvKtd2zL+p5kc2C9/cTdx+3GA2v+54ME6IAVFEq+FL5rtS0Bg0ZO9pMOua
  template:
    metadata:
      creationTimestamp: null
      name: dex-github-secret
      namespace: argocd
    type: Opaque
