---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgCBlxRncrOcJeIdZ8+8oCr7PjbuTsJKiTpLKrDoVcw92tBbIIhBekZg3jRTrUUM6SwNgRhk2ir1hUsLSCk/+wkG+oBfn6VwHIy4SZQ9lTq3gBqHNu20LEWDpQGK+RgzyPR5f+UT+vhy021d5CmvUq6iZu1nQSTw1NDh/qitSwI1/PO1O205gwDTm2L5Lo3nMdyfVajXlAgGWfdTzpCk8NSkWaPQb+LmGPC9hFmA9cRgimr6Slem/2+ilm88/5kkoR6pqL6KoQu/BltstS+b9hYcIUy+gulAVKEb4JKN5tBo+ULY+3LnlcTmtrZX5fpos7S16SZ8jyOexxlukmgGDPC7oN1pEI4EFcFSfWSjEqWL7AmQ1cmVbdNpj/DF+1//F3d5X9DTrjye/4reUvl7wnP+kfYjSXEVNB7nvUlA+IuA6NX2wSO8zJ/CVdXlI8N1da71wTs+PbtOw5oBkiDQg4WdtvJaHMQyVtjCtIsTN0gslsebPEPfU4i4YKcEYIq7Lr4+TUblxh1bC4QPxhNc7A9k47ZeisxVQZLIeM0zN4n/qGWFSXEPTL9cNvcvZv4j/VQwHszoPEPcoxWjyKlYVzCfycNJeZcFPhrdpPCYGhBpgr4Vc7DDOQD3/Z/499qr/1tHoQ4UiVlrcxszMS/n/jPbswI4PAd31BlIDBssC6t5X46qxw/uhPqrezEnzvy5+b9YZNcSsZVsaE48XPkbHDdSYISL39lZ40ALTT6B92DDPhh0cV21uWf20FSO
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: dex-github-secret
      namespace: argocd
    type: Opaque
