---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAWort/FbPPe2rsUHdKMgAHAI3suu8521TRaOLkFFkIiClp62Tjl/9Fz03DnKBnDb2/qyueQnKU6e37EkoT6bzEPXkgAd4NGM2ZrspneSOTDpcwHiJn04S1Rb3o4ORlgFZCendG3gjMuA9tS832psLig1IvYczl3xMq/jbeWW/A9z85y1CLw8EinXTK1Bdd74H3M8YEViY+zTqnX8azxL0Nu9vcCHyqqbkFywcvozImZ9/FfYiJzBOTrNMjKA45wFHQmgegSr1ad3OXqfr5vATgHRs/bufwzMtWCA54TM9bQJMlN4v7iIOoGpX9G4SvMGb/EC07zHIZUKHtQj4z5/J1z089tl1+V4IDsQv3xezNqTu/LMOPXYHU58+lGhdgmB/UqYcBee1tivD+T4slniZOoXDrykuTbn34siPRoINb0dLHe/Fz/YFKezCj4Zd2BYncOqEYtbk4n9bOUzSDbhKLuZ2/vAdp6fvg1pA/drRk5PZPeFC2PSYAUQ8L59Yz6gNaFNDlARMj8j5poPRqEK4guU3qQIgUfYWydhq/Zsg9Ov8c/BRvWU81VYlAoE7tmiWScVXPHjWH1LO3BLmbnE0lpHfJYYsxTvtlboSWWqicmTEPVFFCX7f8IbxF6qp5F9lUR/tLPQTCg7caDLF2Fu1M7wOQAN2TV1hH7PspapVud6i/YT4ixPjMAwsaOuC+ozpTWMOeQHaDLWSdKhOpLK4KWt9SpQd2B4S5oDoZLT2nN9A/epoMzEGlEW8g
  template:
    metadata:
      creationTimestamp: null
      name: dex-github-secret
      namespace: argocd
    type: Opaque
