---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAJm/LaTIfLZ6DX6meJgfqG+yLTY1GVDnEkFBtQt/RO6nIJpC3M6bcxsME57hZ+sccr5XEoS2DobPk0EIxOfInlKgI/NCamLDVF0eJ+KNuWw8gJVebz6yalNoev35GxHaK6UYe1o/cogbpF++xsoBiV0e86T2/0bqwjxJQf6MD3fGDgN3HVHM4EoixrioZNEjSwwzCI+4HnuHtNTCcl2tTFft4V9u+0Gr0uN6gi6Jybgt259NfbndcR5KGHhp4M3l7OMTkCrIS8B6ph3Wv0uYlk38NBYf2foGq2YayrJDT5ddKOFzOoX5eLA5ruFgB5OG20PHGNPyk2rabFTSu9XaS0qomVC5ie39jqrCPP1u4pipbclAojRU0dpQq2ej1Z19YrqXME1t9JQ2Hdc4ydQAHZxMw13VmSL6u0aIc88/UVqfyxAilOBF4yvqEyCGxa75rfFjKZr6SltEbwk0rvMQnbns6NDSuNPpSMe+TzmSjDDRFmm06z4pj6czgodY+fn5beRRTdgtG8hi1Kr6FthgUr413oqjFQLeUU1iTWDiyCYAe6xmp/XPt8BnpjcNiUnmL5muXd+mWZ1df/+W1szi443wnzDPh1c91svS7z2PsLBMD2QyEh/slNKh2ijGFUhTft1o4jMgbbhhdoZrW0rPKyDFHblL2gWtXjTSQ288Q2A4Z5pSOI2iS24qjkeKSyG+7aJllkJbEkxmqSw9PTtwSZMwsx0X0V+Vh8aKLOypn7jam0yTib8/araWA8
  template:
    metadata:
      creationTimestamp: null
      name: dex-github-secret
      namespace: argocd
    type: Opaque
