---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAhgj6drXadmk20wRXWx8bFbb8x9prGsDGYSVhobKqkv7hM9gI4ktaBj9FDxmrQ3gIlJzhCbJdErE4UuDdQvIIam2TY45eWng6pJyFSNVOVRWZdRo6qojpRR4GtfKIrHU8+V488+vGgfLtJBzSU9XDZPs/85j8Ic0tXDVOxZNBMqOVqLJvOrAIoLCFsCBrlfp7eLbQo10j/NLPOQetbr6S3Cs86o7ND5r//6HIFLO49GeziPEAsuacCEfhW8K/T8s9oh1fJl+YMhZRN1pm+ecdmyEkKlokKsaU3agSXSdBXO2cuAS6xfQfjtg4NHfWBVzOnsS4WDr9z5T8tFhHxZeRmqE8w6TQ8racIY/XqJ1Va/O/mjuE6mSebh2mrZZT4d/VvY9eKC66fbeScSEWHqexixAOZJqM+EI1OGogpSUdgEJ3tu+X8mcHgTJ8AMFH+swvRAjyjjrvpZ57GiKXqr0cMxYad1JYl26tIpvNWWPdmuBprhVFiJeNdVkuN+PLHxIHNydsGYi48VuIfnKxGSGCrfZKatFMX3fd08fp7gPHZk5EnaGwrJQNB8m9ccMwu9cMZGKesHlFf2jGT6wu4ovRTyO/G+kB46GFlLXREc02fFqdw0MyOY+YQKBQqK6kIC4Gv4bjGz54WxKE+FXouU4fwua4LsNJp7v6wOWyvrjuvWMsNzOAsISlaVGyD1B5XYM7BBEGEf8tLbP9e5tcGZOGguJhAm4NDk31tdTEhzb/QDv/oWbT/kJ1qKvPV
  template:
    metadata:
      creationTimestamp: null
      name: dex-github-secret
      namespace: argocd
    type: Opaque
