---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgA+gl5MlNSSS1Fq3amxF8JX35LNKQ8iTz5SO0e/Fp/7WSLtbOBY1qLRajflXqsX79QO0xUrvzbuxMmqP8s7MM48JezCCoudkKiZTB4WAAYLS65xSCCY2b5JIT5RRUfqFRRhoWqLDAPD3CL4hMkJ5xm4lBDid+5UhjxgxcuNYihx1wUHxxZqX5neqrcDR5qzFbPkJCfmRk/khB+MuiA7H8imrPt/rQnxf/ztkNRfRTdgoApSHrJGaVu/FjvpAR7/f8nH9tg3yT6wW/P9h3vmWLOjvexE4zIsIKEnSwS0TsJwM1UVFU5Hmw8Pcow2Y08qYCpJoc/8cxO/wZpdX1v2Tir99rC7pVtl2u3eLCBya8LWzzZqcpubxrl/x3jTMeiJtcaJ6oTvyRAKCCUpPSar74guGLj/I90TbKQMIJNdQbtpW5YYl6yqzf2DJznhc/sz/bQ2emogCpbF/F1ybkLW1i7n/DOGtP0P8BnLCE030KyHz3qz8fGTisnyFQMq0bqTF0J6g/wcku5ToALvytkieokYSDT3TQO5IQzqIKAmDKLta9lyvIYj08trK0UygknVmfAlcEA+qzClJND1DCYH1TzdVVxvXQkcfLpL2Yh+y3JCpOsXbdPT3MhCVLiXcmaLV+1JRmu4bYmQQ15P3UJVvG/ing8BcWTqv2zsWyf0sSHD7Fm1lishM0cU+fGEmj0144SXDQdBCN8hxXqpqP+Fbacp3emDNa5MLvqbjyHmjWgmp3YSvw7BRpJbLmWv
  template:
    metadata:
      creationTimestamp: null
      name: dex
      namespace: argocd
    type: Opaque
