---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex
  namespace: argocd
spec:
  encryptedData:
    github.clientSecret: AgAK5RhTW8seCxEmglIjWlSGaPLNgamLowFRgPDnmEq4Y6UfEGuvGtmLGMAUTcZvDnNvCQGa73h0nmdFe0cnUlRZGM0ncQHZI7HWHSjFUYyQOxD1/13kYZhmj+yhxOIcxbmagq7V16UWWQmG4pXN4+TmlJmFS3tU819mgtPhLyDXJ2CewdjyAfv+TH0vg00EHJSKT+/GvnNVH+2jH4WCaQ7ov5kv0ccdx/yExkUcBRJ1RPgrFNHnRjFljdfCPWp+7968sZnuemQU1spDglnEsSjlaXSfTAYLNjKGOBXIjeyV2D+v7NDILc7qVzWM1Q/dKJIZElmAc5+ktf9jJbAkCscCvdR8R/QGOal0VjcIBpFiXEynYFView7xSdoT1s3zh5zyWE/SVKkJbUjYuCJvav975F/hRXvj5WRA85pKOd0IwELltnL2MNBrOJZR7K5KO+yGZc5dqn5HUHtG21OfshxlUM/reUHo+H5bMso09Xs12Hw7InEokwlqa83zf2q05zkQdyaP9+XVRGOdlJjp9CxT0Ln0xjf3j4HLhPWcvVHiZwmToWynpeE8mF81pCgvihwWGefh605xfONL1v7Mz25T+vScyfsiHYKmY2cqcfJJBYADRgwy21KN5uMNoiCLHRqn11S+HmdcPyoSvhxnot7rim3+kNVkY+/TTd5vKGlmtUj9gpKdhxHfUU0+RMAAzmbSAVSMrSKej7vXaMNX6s91HvCjh5Cx3J2bCSzFBvHZjU+wlMsP16HPJpM+
  template:
    metadata:
      creationTimestamp: null
      name: dex
      namespace: argocd
    type: Opaque
