---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: new-aal
spec:
  encryptedData:
    .dockerconfigjson: AgBSJDtT45KfstdHuWJx5mCmpoY7kMdgAkarTIZwgQg35Zyi01xixOPTqbyPOhljVg7oOjL3KcB+jUatHk3mmM15bIpSN3zRNWJV8fYgr1imhxAvP4ZMRrLG0eeUk8+qlLyt1UrBsH/QY0L61Z9JBiaNrSEk3mGfzS2gLjrL/xsr0M7LRKvdhuuIb9LCZ/rLRF+sJEOZA2K65G3CAWKdTsbL//aZ8nOixnCi8dvpQJCZLVOPCpDfkPljlg95a96oCv405zRUDLEU5wVqRc7aEhD/HEDhkHljEPb8TelSXk4mrMkgM21x16l8Amhv5Tv4qXXO5j5llaws2UE5PI1MN7qJcz3p2kzwMsRH/xAHi2Xi+Hi/iklgTobzA/OlCl3E+jdvnHEApuon6aO7jdEVvJLnDT2M/Mvzrge+NvTzPUGrVH7ItILMb1CPPtUkWLKSYIxru+YqausD3M4OK0neCXhq9xFHyrUI0edVHg96bwZJWHVn8/6P7jyeWRByuOZZu6Y+rOhcmPtJUIRzIDjOzq+gdwmq/F0rN8Y/8lCY1YATcyzia7cpK0o8ef1iNLy63YxY/kdA2IeIzAWj2y3j8Owexehb85u4QJH1LXVdBq8J/N3SdDuZAoaAdWIhrcmS6p89JlQJo2Rl11d0fgcLQiTuIhkxgqQ+G1kKYXZrpwO+C94i1plq52dyQGsAQl7dDCFHSrX5FV4KpzJktpy22ColaezB6RkQWL/JVmN0k36AYrG/BfibVrXUUCfHijxyvSgGTTfLpgMRXSo6sFpzPqzOSvm7IoCh5pGF8n1M9UNx6bHLtPloVjueGvXt9fz5o/ioemAQDJr295vSqFbrmh9flWuBNyJOYpxYuRUjMwHnzUwyJv2olASw/RQNM0EXmo1TrN4v/A8No0VfRVhEUmycVilXw37VsDCBPeJ3568JE02Y8u7dSim/i4txwmb5l9TF2aJU+Bu3VWug9mOJbt7h8g7uTH9RjK2+zyddsH0UFEt2RTkfwphR8SH7HgBjxPWn
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: new-aal
    type: kubernetes.io/dockerconfigjson
