---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: new-aal
spec:
  encryptedData:
    .dockerconfigjson: AgCgLiZqmcxMEADwRCZQQX/5efU5uwJHqGrcJAgW26oCIeJFxAP3v8PMq2PSd+UPIK8v/A9JsfZUuh7JpDyEk86Mns5Bm97JSAMgxZn/j5nbgmfqbksD0pNqs4cvVLwHAIL4dQH6P4QVBlOTaoltp9GNz8oBpadKVJortoJGjIw9OMVUvK4H2ik1L1+y19MFNtRFYq0Ii5y4eBAYWzBa9KOxTdrN+Nb7cZDp2el5OCAbNvy2LXVONeQN9nXV/3t1+41syb3LgVnowlo2ezr/xTB+5s0Z6/Mh/BmNsHgr9ibgEOdH+zog31hATFhqtdEHtkUhIuwWhnQSCMhiKQOjAhg+guGfp2w/4K/B4B7RWoVnpsRLA8LMeT8s73lI97jIze8mOzhEH3jME5Dc/4SV7578bNivCxQExBKI7j8RLdxifI4o97CdJqMYeEqs8TXvaDqJtveL8FBfc6BYiPhtXaOxb99FCFbM0o9UA6yNAJigR1tv+2w7ZirM54Sjzv8strnimdL6kAtK1ICLKwh5kQBGEFYDpf/6R3LTfQOoELDnAJDVkNJlRxY2HarvDNCfYZxZtcY5G3oTNQq7/1WY4AirYFnhnCcbby1NSxd4YYlEI/E1LvHs+SGHQfcnGYKRzS3R9LqL+qKkW306QMsybA2lvmjmR314N/vfolwlmToaRRXVVwd1n2Kz6BW2t7AfLNsdmb1a1b690q0IyUBzCQ6ZAVTaBNHrnD0cDtPrmXv1rZrDPW6+R4dgscovA6lydtjZKmse+VMLgMd8FX8zBQpLRBpplWJJZurRn3ZlMH/jQHERuSU4qYSWsm0AYB7z9rJDlzlZSEWFqwUmbqtSnWouy2UKLS9ukZ82QbZq7x8RSDx4lNV1ph3bki5iEYngqvljgx2wuyIdLjTjbfV9kGPRTxHYDEZEW+vsP3x8K+qB0gGtBiZ/tUtxkjCKcQ7zMHhDeWNZaiPewbY/XIEACUTWjk5IqbTAjYrLG9+I2cGS/7Jc1KT63OuVhQ4MuqxHl/Gh
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: new-aal
    type: kubernetes.io/dockerconfigjson
