---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgCZrkeUV+I3XyxwUBwfsxFKp/WE7ddKi1aV/0KkoffFIs3axMedOuiUC8YjAcmLB/tv1d0LvBH1DkBAfe/brPF/sLedJA0uFXTBAhWSqEHzEJIclxci+l+V6p/43Uo7xRYCnBGdkUhxvoDenVyhIbIfmcKI+odBPmSKkQCHa4XxIbld6rGGqSYprpBuRdvi+ETHsI68c5AcsD4/4wzuVvdihZmwJi3tDv8wDv38NHZfMREiYsEDeC28wTmhXd5qUl57IGLQaHD3cFWbEUHbywM42h6enld8v2tTpp+snIvMX6ZI/8Bq+1dEwwPckp1eY1muujFJtWxvRybVBD3JlFH99dp+mI8bhcti8jYixCsqRFKum6bJDS4vViUJ7lQOZTTJY6dgjCrioaJZ6sSVSsbRl1Of8+pNjBJnZ8YcALrkmJetEPVLcsielLsjzLP1R+kRYwTT0geyQ2NH2khbFPRu66NiBB2KFyyesrBodYHbHyEgmSlvFIhU6vBycFhXCvyaQbBDeu1TXPmQY74lNQtndd5E6mRwfWm6OrKvkgfAt4lmPJ3cNYReLqC48tGFfxdzjYt33jmpenBc4bt/TE5NZmxt6ugO3RLkT1wWScyIdPLWOf2eiQMduX7OTmTvZy6PqdS3s9b+zkpE/XgcbA3SpbB7U7j2PE3z9Itd5p77i+CnjX4bj2Tk4dprCJZrowJHdfPiD5XcLFQ2Jou2vgY2lUF65v8CqBMGfZejZMhql4xoxO+EK3w07vjZmc7tHK9wzZmzXQ7bRswQgA4tsan/kMem6aRSaZG8jP3lM+zx/qYhdF1KOtWGjyGov/8KXY1K3FC9/jwS5yhbbvxnCJnoHv/LLsSVeEZ2dUIHxadZaAG9eNXlAORUBCl4UQ3BFkmRjYMTsjFTuPJz1I85f/VSrs1Q3Ul8uv3D/dL/KdVr5VpTfdgc6RkCxeV15D3r+uK7nM98HmNtQ4u7X91vQSbXJKRkLc7xomfLEdaShqtMnwLEnqodz8gwlAvMk9JGGp7P
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
