---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgB4Xn3oafB9HSBCEnFOjEVP7mCbzlu15f9saVnTqhoIIu0Y9NwSucFQhYiw9pBOeCPACt/ToXr0bQaLoKSt0WgCvF91C3J10ZixkJm/CxkaxBz6hdnwA+xcoqLOzSC/PbLe2DtV6BJJeB1eSC12lh3xlRJPIqJmszK2AIZGnuGFCb04ebtMZb6+iMMjZfr6BjuWMvx/XmAJt+tM/yRB33nadYSjrNfSdmTAoFTlyggbefbjYAomtWHHIXvqmYnyG9knHWoCHWJQP0U3CyYzL+GDvQuwfe5w6cDB6W20q+BoHay4PfmcgawqesEW2aq5KxL2cZjz1OUU8DDz5gSY5mZMacUTyLhpoYxXXsjhwPgrXyTELUnQ1qsLkT6nXLSeLhersZXbJc3c1W/ozr5+Bowm2C34t3L0n57Q87/8BQzW47ud2prDualaD2+3jP/vQs1FOZz8SM9v3BGtxwInZt/JtJu05eGyfykcw6Kumg0K4mqHBA5NXQPKh9a83xsUAIjL0Z0zkBFRaYTXT79dofCHbgaWeMLR0tH0lJs6t4ex37nsjRYrq72yDdzgJIsXwuinqomJHpfa87bid0bJI0UlbTea6Z4685dIqqgIebJsr5GFrpjZXHRNm5WkHvyp3Mhox/EjkLBYjvRYQ/O/4NTe7dMKiPxLjCt+tq0rmuZy+BdY0GssVPbhemxIhhp942CvryguLashDBG6J3KTpXsCIPEUz92dk4HAtlkWihjii8Yagrz5evd5Mud7e5pRrSYIKv74WZCj3LUp603dIFPap01cvs6cbty3A1UbbkAVp07gUeaof77DfR8bNX+94eyE1dwcHEzpYFod7JSNJrwT29u/qY58zdzpqAekUiNYgKDje11Uu5eNfOlzf/fXBdryJhytJHK2MOYYM4jr+4ie47Eyyic+xsfsNkeR9iv1Mn4SXbVOcypNC8kzXh5XguDDTR2Rxw5wlVHZwR4v5PWv7WjQ2AGbklGNwIs8VMqaSy15PAq2PR4Z3pU4ahSoje1a
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
