---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgBTAtQfLSoWCYa1CbYH4w39j0DrQTXH8Amd7lobBB3eYy1fAhYXvGKy1TVvq466bLxCwMxgPHFtFK7g5pWblj63EXnPlRJhNweVzz0uUdjGqPBqodtLxL3mrvzYJzu1fovskvvBLdp/D/3D/+xeaxqAqZT2DLsIQfKaOc5v/1UZTmNR4+03tFm0lAFDLt+V4xCGRtYMSUn5n2O+pDxYDZ/MwT8BU9jRSeLjH5BCFGD4Uzlniz1cf/PnLi8gSZfUyyyJXAp29Dz125BNSUdUyDk+DkdWaG+T86ZsvX24ZPC20rrcdUzzkI3paARR2C7t2AbWIdai99gtR54QZlVD2Ll+4vqQ/9do9BeqzoiCgUwIf6iU4yj90/wBW4x2fU2qGWHS9/Jl5ML2qkGNmsWgBSwyMkLhNVQPOMCV7jOqZLf2xFRHKBd1cE3lh2mrj5eyvGbSPso5FzAMvZabopURzbAS5XSkpYptjWWIGlDFx+BkSgpS9cQ51k4VAl4CUM+ulYPQ6IViCvJyfhTuAw0OnWKYON3+A/bMbDykmoyVJ6Vqf/Fvvao1+PpcA+5ib8BLzxZi+TPqxDENNLxhFQbXICBo5LIk+NaX2YIBGTi9jMfExX5jh5JbyUy+C2AwbHwNTD2JbffiOMV98vO4yxgxq1JL6HqGRrbnJUBlbGs7ojK+1QCjDcAp3moP0Jo+vAS/BxVw2TVLqNyHLrzpHNpxaJsEasaqTA==
    client_secret: AgCOutsiuja7D4+amr49N/slY41fGKzIHdcK5ikAZaj1WKzNvCitMShl7kTyxXVzr/7ncLDfhUOVl0c0JUy992S/pe6o92WApaslNe+0SALQ4jsDJS8E+nCXWhowVZTZLMjXav6Vs+TVgZyVDOGallb9W/7F1XL88zl0ivkmci4JSZ1aglvyIPLiP3nQT8YqRPhRvEAMCggEIZ7YnMb7bsQb4OmfcmKRXL4rsqdX3K9OsB7++7cjbFE7+BSrcSmeU58MuIxE35N/naIf72xusee4tpuKJcSHUwZcyBgrunO7wMuGYnr5hHdIawyDBixALt01j/iuUawfOW2nsUozAe3JdOSPIIsDmXQHautKzkxz8LdEnO6pd8JzsjDGIAK5XMg3spAzV7XaBkDjkf0xEsBGgFT3a9ZtLDh2CA1AarqxG1bVL4ZjR0ZgAcI6rgynsLg23GKFy+apQNPisSp0Fx6MHTLrlsBBC3h1Yno7J4ZDLZ2Yc4oMgf5ulk45qnJGnphyncttN+6gFb9oT+48XOvHm7lokVysPlc34/+mqx2dAji15DVsroixtSAj7c7M0/MtLZCiZxYiYilxbBdXAS3mbqNv2j++IEw6f8PtEAYvFKW+cVSxYs00mQKqOU4tEnuQ5Dos0c+sroAeKiXdsEQJvmjeVnefyWVWDfvS/b5e6f8KwFury+XZ5Biujqhui3FeEmnSqbXFMruYsRELzEvEZoNpzK9bCKUOM/Prv3WWw3IhDz03Ca2N
  template:
    metadata:
      creationTimestamp: null
      name: github-oauth-secret
      namespace: monitoring
