---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgBdX7wdnQuGnTJlsiTJwY0S2ixp6RUJM14vGRmRgdcxnGt/wnAAId0drQWe06n3CqVyGPt+n8tle+FWaufgMDLtSXImTzyk7emYnyS3y7HIXcGSAMTcNhLSOEJIYvCODN4zDENe/+l6E/d8Kp/JD6YHfWVUOhBOzahaJ64CLAwYveuvoMi7uaIVXJ2a6xxEAe987agb7adyBZKQNdv+ExIl5PyxFrFL/+WWsXGX3U0hpPg2O/6xRqqshJOQw2kNZFkKdq0UMFFwg7CbqLPanAySqJfQ2caFkLqf6704Bc5kk1DmkwuewQKrL5vMN/XsLG6b+kcbgQnD5Z7L1x8rex1W+2JYbJEaSXRInQFqw0fJmSXfsm/ufuq2GPyRtVF2irW0W+giGxrDIzvhuy7+9UZz2pX3KmT0rEyZXX+35IyMnh20BH4SLnz9xyMBb2Y5SoOFs7jM864ynE0YoIVPPwYj222uhzVcAeAbwWrfF89gHpZJNfUP+z8eRaB2I0cfVA1EhKbR1/Z8h3Uy1w+nWblDhOy8jxvmvuGbffhbCiePKOadRlKxB8wiy53xmgtAvA7VpnaxuxIsqjD3NwSQXMi/r2stexzgZSYyw86KpaMuAkmD84vD8UKQTamvoADFcMOf/prwed7Bhxji6i7q+LOKSfZDxr8CHAqVdYPKgGqSM1f2EsYTBZrIbTA8sE8fAur8nn519vSkLuzwLbwywPFl2CeXig==
    client_secret: AgDehaj9YqFS3KEwoSLFiOyZEC8s3bj144kk/b7CC0rSduqsAqwN1PEt3f18TW/EK8NKAe6gimATGSYX06Q/WiF67Yh/0s7nY38Zt1/rWliYbS69i9I1xwN2ZlqouxBMWi98tmPM5fPUn8K0m6UU+fcxEB8WJHhX4F2s/P/iTkHbXfusmnlw2uW5twArtJ7hkFPsdc898SylOGz62p+gPvLmDaXRr8v376qJQP1kYSVwBuUytXfKNXxmXxEK1BzUR75SGzRRufIZ4U+xVDsEfE0pMMRXKPpuUBId1Ul2oyDS23xKrMzQN5gOPbDpqv67f4BWJ/Ea672waPUXc+0SGp7+LlJDSPs3nqJNrQw+cGP3LxbQdVxNdXbfVrTT3RVr07N5Olqn0C6f2TuMHN9I0QVRW3qJiWF/V7YixV9R8FIBLep+rw+vCYXJ4gHXkdQ5B+NdbscvJ/mPY4NO9w+VURHobR+F34T7dIUsI51DfZwRIZVn3NbmABYd/qucfNlWo0nm9/ApHXLpcYCNcSBebp2+W35yVyPkjzW8lgZbVqqRq0p5KI5qb3MRCUhIqQ+teGADMdtVUdSWBn9jW3DO/pHDttIJ2mYIlhZD0JWN7kWawzjbuB1Q1T+/kTNJeOZ7chxhurClDxSujvt4xxhgR9ksEyt11+Qty6EhZDnubVIKQnW6p4cI4SOoBdmCSHtiFcfusJQFlYcSzVx44P+HYuIGs7DsSqqMc4Bl6qGT4I7vmbFPAIAiDxZ8
  template:
    metadata:
      creationTimestamp: null
      name: github-oauth-secret
      namespace: monitoring
