replicaCount: 1

name: job-winner
imagePullSecrets:
  - name: ghcr-token

frontend:
  image:
    repository: ghcr.io/januschung/job-winner-ui
    tag: 9ebcc04
  revisionHistoryLimit: 5
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 80
  secret: {}
  configMap: 
    name: job-winner-frontend
  persistence: {}

  resources:
    requests:
      memory: '64Mi'
      cpu: '25m'
    limits:
      memory: '512Mi'
      cpu: '200m'


backend:
  image:
    repository: ghcr.io/januschung/job-winner
    tag: 9bc0f16
  revisionHistoryLimit: 5
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 8080
        targetPort: 8080
  secret: {}
  configMap:
    name: job-winner-backend
  persistence: {}

  resources:
    requests:
      memory: '64Mi'
      cpu: '25m'
    limits:
      memory: '512Mi'
      cpu: '200m'

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: janusc.duckdns.org
  path: /jobwinner
  pathType: Prefix
  servicePort: 80
  backendPath: /jobwinner/graphql
  backendPathType: Prefix
  backendServicePort: 8080
  backendServiceName: job-winner-backend

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
