apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.name" . }}
  apiGroup: rbac.authorization.k8s.io
