---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: observation-bay
spec:
  encryptedData:
    .dockerconfigjson: AgBEDTtPlldj5jR8kmj2JcBIOpJmivxuYnaZr687C59bZgKVvZ6VKYVCJPzlMKpPE67AoeHd4Fh+wEUnF/JUcTvwlben6eqZvlpu8pyFvAExyzKU1a1HECHe8yHYFvjVXFO6id8syHp41zlY/EUMGl+cOG0CnlSYx2Ao7M4qJODwgt0SflOpXPDgSLOJOzRUiL3EF/bqmqTY9wfmqvA92GQTjPwBou9j8tlbdZxmi1IX+PGHHbVQFbEnGsX8vbxlzFpNhSVlExSzJc88nqWyqQhAqATqa0e1kEjRRHF40jVEtzJGgHrZZT+AgIM3HHXO7E9FAwCvMLHN0cWxe7cIVjO1iEZbgcF1rkRPxv7yfyZGPfbGwH3e4Oivhlribp/r/PxRRiz9sx1BnatC21xI7M08BejHsxaK+95MP7Rj13K4R8EHPw6IE/JoJpVZBFKVD254GER6aG2lvf6eR0xUgFtzEj0yBQPZHy6GjF3srmp74DilXmj8qC7hOSKOBM/DkTSZPfbA2ZUMhKUjKLbDwKMztUDo53c28bOrSEBFsGNs9Zmy0xM1iJr46Pz2al0j/QWEVDdZUoJLm+QRQrCi40CMz6TJ2Lkybd+IDxKlWzPqNhUIbJBMyE+6tu0+m+ZLEhrmCaVKuTcstOBoOL0FG8xxClv4OUqs1m80jw0LBf9rr6vLtoBAJECzZ9OWWnUq+fuN0cFy0Go1AL8pDS2AwM4iz9JcUgSQdtT0TbtT8M6pYIf1rdDzWIZrPVSpTk7soqVx1llmLaINj0oyhzTNtirUfXIgt/mydds8/4wUrD4/ZFButc5RwNFdIsy4A4ompDtya6QMStDaqJfkkqvghn4TsZRl0tF1gUcCpGyOy7CnU77spc13CNHCFjtJgWY3Tfu03RcWreLzrrodrP7PQ1GReVWRrLqekYLs0mHi/Z35GpQa8u5qY2RUYWc7/JxpJu7aeoFH3i4XLfxx0gxml/stXs7d5fe8dtbz5CApF3HDH5W6Tc8W1WO4SmUls6pGeSoO
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: observation-bay
    type: kubernetes.io/dockerconfigjson
