apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "app.name" . }}
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
  type: {{ .Values.service.type }}
