---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: aal
spec:
  encryptedData:
    .dockerconfigjson: AgAtjlyF+pYmPBY6OxcBZelFhxbEA3dQtWaq/as6XrkVCpZIjH8cKF5Qv8PBut3ZyVOye1M79rf38FEJtImAXKxn19gaGtFvFjttOakARIXA+jA1drudiwD5OohO+jHVuV11U9LEHQiUKK5ubG995IrnXdmaZW0z7Pqc0A2g9C6/qf2256Y1RXOeOZzyICwS/UZo+z3SERcJ0PpcfctqvbIeU9mmXv7YJkSE1208CkGql4oNcDiQXwMol9GzPfyogHwieaXk0H8zwJZK3HZWLUhieYcXLLtTggzqRpTs2zIvJkeJjrNTjiz4brVVtW4zsucbcNDFNJns+Xz8q8d+Tn3uP3cW0+Drif55tx4IQKRHjMWXqncQ+AXHyiO2oJLP45qoC4ab6YNSOKL8nOgkmhcESkEJfSx/Z+yzlBwIieiFm6WPjoV5PKKoJB5fKBmgYNHq/0LO5WQWAp4Q9Z8Ph5Is2UrJGJ7BZGX5AmC0uNegwR/2Pqq+84x6BDWy2iyH6Wn03cyZi+yTATeAuKoZYMxsuu/laVo9Ht+TM5wsqv7Yvx8JlX1nFN2L5rSBWDWm+DzcV7FjwtTO5uWVQuMB4RbXk+7szVDPWm41AVJOcz4An55FjDa6bjKHAddB4oNp9Lb2+1fsxZ8Zz4GEthEdtueindgRJIM+ZnvuOy6T2v499wXsHw4S5GBqQy1E41eoZOwjSbOMjisyXCye+hIOGskM1H9+PIZSINjT+dh1vKjK2FQiW+Zzlj4ahcQFkL6HUrTPkwECh/WFz1A9apXAphN3u78vDYNvNRFu8/HBL+ltFdpe3x5znSzKVSRc0MoUYLR6aXun6TsMiETdoDXX3CCUxLK9o03cHqia9JkjWirt8KbarfAra6ODEYd2DDq6h0RpCk72r53FLPI4SronlPL0e5eOUUSEapQaVbuMQXjeHF5cqxitt5W/iwwyhiKFYu78NMazWrU1WUMW6WFfV9FDew7422kfpqrpew4zPr+KrHO0GfTDZT9i+EEAzo85jP3I
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: aal
    type: kubernetes.io/dockerconfigjson
