---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-github-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgDdvEqaVKpfv+7IiVppi1QHfvHhRZCIL/OuOlqYbWiaYQbpJcVejKsWbNhsrzsSdsNAVzUOwYDoFRm5PTpU93kqlWTIGine7XKi8ql1ogfVoKCnyEz0XZCOF3FVdQiz2cZUdU/5P/kFKYaFbD4OK85KPLXjixbMJigJLd878uw5YrGkBYgGbreg6GkaShwiHWlYFfT5b1B6xft1tA92R4z0bzHmsglMf5d+YTbCOAu3n5JLXBRurqpWEF7O3KC0a7otZtD5c0Qutdj8q8RMi1L6jOP//zOPE0aocZIgtGlLFNvWTtey/ZIZoOg7OeZMuzqZT55FFvW1az+CQjVOLAdir5d2FEtgJ85nVyowWOpXH+erh+0Ul9h/kGxLbAsfv/nsBRxkfo/O1IXjMJQ9Lu/DcLSd/euuepcab1mr8TEsWQbX4NkL5gTDdc+IDteGxeSN+JM+BJXu9/8LsUHNL1WfCqYhZS4rz0b/buY+Mv6DMfi9rrVGAaIygkTR2ceR3vKG8WEu84R9dqfqG+i3FGTYi4xzCB9wl/IouAsyeHr2Ebv5A6daHxNVwxZkDbR4z9iwN+Y6W3lRSxTRMFqwObEv6eSrNgR1K0H4zkDj39s8vBYuvXXQWpiqxs7VVLf77EXNkXLuT1OpO0HqaMV/I5lTs3zFrJEL6eCTloDCmkdtYlTk/6QsO0GcmYIpE8Z5kTmwjY2nrvDpXHUGPnYHti9VneZ3yRrMGRbVgToURSlrEt442lvJtoSJ
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: dex-github-secret
      namespace: argocd
    type: Opaque
