apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-backend
data:
  SPRING_PROFILES_ACTIVE: demo
  UI_PATH: https://{{ .Values.ingress.hostname }}/jobwinner
  SERVER_PORT: "8080"
  