---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: job-winner
spec:
  encryptedData:
    .dockerconfigjson: AgBL7btuMWCxcmIJfIKmho7Hn8Ly+08TD1RPT6pVbsbbK15cSRMtmkGoe+yCF9oCLjpFy8VYtxexM/h4V1ggxApG70thinlklXaIrfvZxzPdjEqPjyB8UqtZrVsPJhKBWwE4rb6TdUhdD4B+u7GkEyIb4e8NFIx4o7saB6etrZqt5EpM64PnU7JfrMF3Et4l+OFD54jhIQFOODoDiek8xLx5oepXb64ck/svwrZo1dDaWyT4txCbcssjDxYBCoRfzQvjCsvDW31FSOWf66mHp83j63i4XAP4Cvh68XKy2hl516cDeku2CMIoI0BJ+dsz+3minb33Cz2vgaqlj7sxyNsYvvesH+vTXdS8PL3fVY1xuuQ4CSC+D8KRlwvGtexiuIhrqhTQPaN5nrVN2MjkVc3ACebF6VpxGcnE9q/+ofPJzynwryg5C1b8z6L++f+ss4ZvCUR8zW8geNQkSJVJQzPqWnnyLRme4nvmtNyLC2ZyC/XrsckMXaacQnfYfFQyKOlDXvh07bYoys3Ax2t4UdCtN5y7+9e9Lr3CVvxpIk3IV8FWCVxt1pqGIGCgdk1LYEMalXi1643v1Iicmg0sZMPENK9JdXnaaWHL9CGCE7miXGCHF3tuEcrCHFGXKCLm7KXPQWEe7J38d3rKUlfHTbvRywzF/nVRczjT2eUQIhRMMa4UdiRmetQxbzNcPEWYPQSMUVNTtKSpJEigwg+Rv/XguymWnWwXFjKkS6EwVXLJT3HlDpZqWTGqCRkLZ/suReLsVNA60KRlY1t2anWb5KZsK/v5GRWeeNPpHY4LG8hNJs/2wRbKTPHhCT6++7lKu0Orsm36r7P0tfKUmE/+FUjgTOaGQ+Rjc1NzwSA2EufYOBcpl9klGNnshADmY7qPwFjIYWdPq9CX6yCFl7RHjpipoMVMoRptVp/BaiiW587+VvFG1bsORUoAc0SLAnsLQlZTnk8ROpR+nnBtey3mL5zrgsEVm8qIhfZH64ODF+yFJ5wLbbGHj0mKlUyFrWTHj71n
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: job-winner
    type: kubernetes.io/dockerconfigjson
