---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: photo-show
spec:
  encryptedData:
    .dockerconfigjson: AgCdo4OGqNCHVQCjjtLN3Doh9r6KcKaSGijFC0Wv/D+gWahP2SulLNWJbuLzl+Y7Xwr/hCawSxP1KQ77IkvkZofOQMFal7QgAqdSK2v8XiRWN3LRVF81ZSlzMASR9PJyrXp15M3zzxuKGEBGDVBUbzQKLSqCrGTN2K6+PrSWEhDViXMN5ZUetVyrMh0w7i6seI28Eo9+PytWyvPzHwXSM0CPa11RIqHiHaxCo2IQIgT+XZxZI8B1wG854Zbty/ew0n0voZ0Whre2XiyRwpVUNwAq/BaCF+AH9X7wBwpRHrCFd8naCYK1+0iKsdnXw1oZbE7p0bvI61AFlZEvGgUbse8dFCBUCGI1Tan6Vl5FCJaa/vlo+T9oM6t+SKh/5cJqVyU58l3xDEbZ5m+l5QU2xPOrCwp8pKOU5UOUPXi0RmLxEyCZFu0WrRn0/LC4eudtDXhU9/+bNPp702DqpQFyBAyQ+Qjc/DzV5l1tlIfsczAymtyjXEwQbUg5D5755M8ROZ0I0CL7o4FHcgSSsIL6A8NpbDZhWJ+wBoCB9GOz6ytKqXNkw57fDs75EJ+V92uUciFVbWJWe9l+Z4/SGQuKJQrzatS5N/KcT8+d/s4bg/eJbgFhzT2BU+7aX8BTVVLhsxCEvE1YN53mKUk1rAbarGhTe6PcC2NR7OCg8YsL7BkKlZoyclXCKC1iDiAM6PxIQztyUlLQKWMgAK5oREi9DRfg9Lm8MWG+HBW1DVcZICB2Q3Agbk72+VWh3c/2L4fY0WBKYukNfuAbdBwUBwQ68MzfPCsPTVVeGIq4PWJYUM3cdVbBmqh3A+q+RvQrTLls1R+qBz2L+HTEpOhUzO1JP7Gzk9VVIvEdiXj6ynovyv2NambVYEV6BhkKpahXnLoqY/+kLV0zW3DJEIHksidLrWllkgmX5HT4TolMeGnDhYr1+ZkPg7cI0jf/4iD2/KVeKfmgIW8IWmod5Xg/6MX+33+hoaHhmeJVHKuWdJSgJktokZ29rN29l05oBwcwnk8D7IV3
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: photo-show
    type: kubernetes.io/dockerconfigjson
