---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-token
  namespace: photo-show
spec:
  encryptedData:
    .dockerconfigjson: AgAkUSJPT802jVsSlqcDgPJPwVEVDDEGhab+JDfygJqkENjM+ruHiZdaFGjhgxE9F3OyhN34c3xaj9vvH2CA7HEPSaHlCjpBHdHLSFIizvd5PexRV4n89TDnuOjoNHtyXH2BgEhZiYOoeF8mqX4eTrh0OBXkjKunHZxaPymBKe1XHc55NQjOsny8wgg15HHAmAs2hPdu1taK1G0NF+JDaXJqVrDbr5DA5vKSeWnRyunJ9f7H+Fa3FP8p52OPBEz58IWokxlBGnghuRz79hGub/KSUldFijS4wMVSDJswZhNHPn0jdbg6K0eaxE6Vx5dYQo5m2ROR/VDFL/lVECryrzhuhaPHg9WFtbB223MUyGxoGpyFB4Tcvep/i8f5SUfABXiifH7LId/aciHXBY13ptb3y7ZDbdsuFCToK8UCeAsoxEqxYjb043GkCCR+PT2NZoX8hQrnnkanlXL07nmeiwACtTDNhYRbXHbArqX/eMCAm76nBokkTmFG2F5J7lPdAzuDjf3waUc7yH0w8HxJgP8yCj3aZ18kBJ9Rk3jYwyh0LKAtNx2qQ36LLm7Eietps0/9BDpUEOvT1H31AEFQZcqbkWGDyrEI2qQnpApWZiTdMwy5IDVc1+ETed9S/u1XxOpHCNe+/naysT6JtSuCysI4FC9q3XctXqIq885J1tFnJ9NCz6we8XhNOLek7vh7Tg+JHTh2Ey0u0fh6/Ix0ilIoEqi55v8OwxJkney7jNZeLmRMTcwoeAy5qAqRHsJ0eX07ayOxkao3wE/nWIfdtNLUUavBDH32eGI8u51MFt7rX7URmG1aqn9n5fu8A8ASDotIE9M6ziTrkWSivLLqBtnHBEw1g4KJUhOarRMkqL78ap+o08zlxmEjEsTW4DgaaljZ/VMRWnguH32dGH+t31ifyWax/7XCOIKkUS0+/ZUHPEdvO0SwT0C3gK8EmUEsM0IvzC1rjxoetH3ESEy4av9QmTfw2233/iDwRiUZ4zMh71IAbqH4WPVMSma5swrhWAH9
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-token
      namespace: photo-show
    type: kubernetes.io/dockerconfigjson
