nameOverride: argocd
fullnameOverride: argocd

configs:
  params:
    server.insecure: true
    server.rootpath: /argocd
    server.basehref: /argocd/

server:
  extraArgs: ["--insecure", "--rootpath=/argocd", "--basehref=/argocd"]
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: janusc.duckdns.org
    path: /argocd
    pathType: Prefix
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    tls: false

repoServer:
  ingress:
    enabled: false
applicationController:
  ingress:
    enabled: false
dex:
  ingress:
    enabled: false
notifications:
  ingress:
    enabled: false
