server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.janusc.duckdns.org
    paths:
      - /
    tls:
      - hosts:
          - argocd.janusc.duckdns.org
configs:
  params:
    server.insecure: false