server:
  extraArgs:
    - --rootpath=/argocd
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - janusc.duckdns.org
    paths:
      - /argocd
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
configs:
  cm:
    url: https://janusc.duckdns.org/argocd
  params:
    server.insecure: false
