nameOverride: argocd
global:
  domain: janusc.duckdns.org

crds:
  install: true

configs:
  params:
    server.rootpath: /argocd
    server.basehref: /argocd/

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    hostname: janusc.duckdns.org
    path: /argocd
    pathType: Prefix
    tls: true
    extraTls:
      - hosts:
          - janusc.duckdns.org
