nameOverride: argocd
fullnameOverride: argocd

configs:
  params:
    server.rootpath: /argocd
    server.basehref: /argocd/

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: le
    hosts:
      - host: janusc.duckdns.org
        paths:
          - path: /argocd
            pathType: Prefix
    tls:
      - hosts:
          - janusc.duckdns.org

repoServer:
  ingress:
    enabled: false
applicationController:
  ingress:
    enabled: false
dex:
  ingress:
    enabled: false
notifications:
  ingress:
    enabled: false
