argo-cd:
  nameOverride: argocd
  fullnameOverride: argocd

  configs:
    params:
      server.insecure: true
      server.rootpath: /argocd
      server.basehref: /argocd/

    cm:
      url: https://janusc.duckdns.org/argocd
      dex.config: |
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23liIrQ2JLk0Bwvl5O
            clientSecret: $dex-github-secret:dex.github.clientSecret
            redirectURI: https://janusc.duckdns.org/argocd/api/dex/callback
            scopes:
            - read:org
            - user:email
            useLoginAsID: true
        staticClients: []
        enablePasswordDB: false
      
      kustomize.buildOptions: --enable-helm
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            return {
              status = "Healthy",
              message = "HACK: skip health check for Ingress (override in argo-cd.config.cm chart val)",
            }
    rbac:
      policy.csv: |
        g, januschung, role:admin
      policy.default: role:readonly
      scopes: '[profile, email]'

  server:
    extraArgs:
      - --insecure
      - --rootpath=/argocd
      - --basehref=/argocd/
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: janusc.duckdns.org
      path: /argocd
      pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: le
      tls: true
